### ISSUE TITLE
ImportError: cannot import name 'GAEngine'

### ISSUE THREAD

**Issue by wuguo2017** [PytLab/gaft#44]
我的操作系统是Windows10
我通过pip install gaft安装了。

但是在Spider下写个语句
from gaft import GAEngine
会出现如下错误
ImportError: cannot import name 'GAEngine'
后来我又装了Microsoft MPI,仍然出现以上错误，请问怎么解决。

**Comment by PytLab** [comment]
请问你直接`import gaft`会报错么

**Comment by wuguo2017** [comment]
直接import gaft也会报错。
错误如下：
runfile('D:/python/untitled0.py', wdir='D:/python')
Traceback (most recent call last):

  File "<ipython-input-3-92f360ad8b0e>", line 1, in <module>
    runfile('D:/python/untitled0.py', wdir='D:/python')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/python/untitled0.py", line 7, in <module>
    import gaft

  File "D:\python\gaft.py", line 13, in <module>
    from gaft import GAEngine

ImportError: cannot import name 'GAEngine'

但是通过cmd进入python,然后运行命令import gaft 不会报错

**Comment by PytLab** [comment]
这应该是你spider的环境变量没设好，请检查一下PYTHONPATH这个变量的值

**Comment by wuguo2017** [comment]
我用sys.path检查了，gaft的目录在里面，后来找到原因，原来是我定义了一个gaft.py在当前目录里，import的时候首先到当前目录里找，我自己定义的gaft.py当然是没有 'GAEngine'的，我把gaft.py删掉或重新起个名字就好了。谢谢
